=== millenybelusso/millenybelusso.github.io/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (address, contact, hours, mapLink)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT mapLink (#PCDATA)>

=== millenybelusso/millenybelusso.github.io/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">

<branches>
   <branch>
       <address>76 Devonshire St, Surry Hills NSW</address>
       <contact>02 9211 1234</contact>
       <hours>Mon - Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00</hours>
       <mapLink>https://maps.google.com/?q=76+Devonshire+St,+Surry+Hills+NSW</mapLink>
   </branch>
   <branch>
       <address>451 Pitt St, Haymarket Sydney, NSW</address>
       <contact>02 9262 5678</contact>
       <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
       <mapLink>https://maps.google.com/?q=451+Pitt+St,+Haymarket+Sydney,+NSW</mapLink>
       
   </branch>
   <branch>
       <address>31 Alfred Street, Circular Quay, NSW</address>
       <contact>02 8971 9101</contact>
       <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
       <mapLink>https://maps.google.com/?q=31+Alfred+Street,+Circular+Quay,+NSW</mapLink>
   </branch>
</branches>
