=== millenybelusso/millenybelusso.github.io/menu.dtd
<!ELEMENT menu (meals, beverages)>
<!ELEMENT meals (item+)>
<!ELEMENT beverages (item+)>
<!ELEMENT item (name, price, description, image)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

=== millenybelusso/millenybelusso.github.io/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">

<menu>
   <meals>
       <item>
           <name>Beetroot and Feta Salad</name>
           <price>$15.00</price>
           <description>Suitable for vegetarians, made with fresh beetroot</description>
           <image>beetroot_salad.jpg</image>
       </item>
       <item>
           <name>Sourdough Rye Sandwich</name>
           <price>$18.00</price>
           <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
           <image>sourdough_sandwich.jpg</image>
       </item>
       <item>
           <name>Spinach Pie and Salad</name>
           <price>$20.00</price>
           <description>Tasty pie with salad</description>
           <image>spinach_pie.jpg</image>
       </item>
       <item>
           <name>Feta Pancakes with Salad</name>
           <price>$19.50</price>
           <description>Tasty pancake filled with feta and salad</description>
           <image>feta_pancakes.jpg</image>
       </item>
   </meals>
   <beverages>
       <item>
           <name>Small Coffee</name>
           <price>$3.50</price>
           <description>For coffee, please inform the staff of the coffee type</description>
           <image>small_coffee.jpg</image>
       </item>
       <item>
           <name>Regular Coffee</name>
           <price>$4.00</price>
           <description>For coffee, please inform the staff of the coffee type</description>
           <image>regular_coffee.jpg</image>
       </item>
       <item>
           <name>Large Coffee</name>
           <price>$4.50</price>
           <description>For coffee, please inform the staff of the coffee type</description>
           <image>large_coffee.jpg</image>
       </item>
       <item>
           <name>Soda</name>
           <price>$3.00</price>
           <description>Refreshing soda</description>
           <image>soda.jpg</image>
       </item>
       <item>
           <name>Fresh Juice</name>
           <price>$6.00</price>
           <description>Freshly squeezed juice</description>
           <image>fresh_juice.jpg</image>
       </item>
       <item>
           <name>Bottled Water</name>
           <price>$2.00</price>
           <description>Refreshing bottled water</description>
           <image>bottled_water.jpg</image>
       </item>
   </beverages>
</menu>
